version: '3.8'

services:
  backend:
    container_name: atria-api-dev
    build:
      context: ./backend/atria
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend/atria:/app
    env_file:
      - .env.development
      - ./backend/atria/.flaskenv
    environment:
      - SEED_DB=${SEED_DB:-true}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - shared_portainer_network

  frontend:
    container_name: atria-client-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - default
      - shared_portainer_network
    depends_on:
      - backend

  db:
    container_name: atria-db-dev
    image: postgres:15-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - '5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
      - shared_portainer_network

volumes:
  postgres_data_dev:

networks:
  default:
  shared_portainer_network:
    external: true